name: e2e_ppo_trainer_megatron
# latest version: Megatron-LM core_r0.11.0 https://github.com/NVIDIA/Megatron-LM/tree/core_r0.11.0

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - v0.*
      - lusz/mlp_ci
  pull_request:
    branches:
      - main
      - v0.*
    paths:
      - ".github/workflows/action-test.yml"

# Cancel jobs on the same ref if a new one is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# Declare permissions just read content.
permissions:
  contents: read

env:
  IMAGE: "verl-ci-cn-beijing.cr.volces.com/whatcanyousee/verl:ngc-cu124-vllm0.8.5-sglang0.4.6.post5-mcore0.12.0-te2.3"
  DYNAMIC_RUNNER_ENDPOINT: "https://sd10g3clalm04ug7alq90.apigateway-cn-beijing.volceapi.com/runner"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: create-runner
        uses: plutoZZZZ/verl-github-runner-demo@v1-test
        with:
          mode: "create"
          faas-url: "https://sd10g3clalm04ug7alq90.apigateway-cn-beijing.volceapi.com/runner"
          mlp-image: "verl-ci-cn-beijing.cr.volces.com/whatcanyousee/verl:ngc-cu124-vllm0.8.5-sglang0.4.6.post5-mcore0.12.0-te2.3"
      - run: echo taskid "$MLP_TASK_ID"
        shell: bash
        env:
          MLP_TASK_ID: ${{ steps.create-runner.outputs.mlp_task_id }}

  destory:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - id: destory-runner
        uses: plutoZZZZ/verl-github-runner-demo@v1-test
        with:
          mode: "destory"
          faas-url: "https://sd10g3clalm04ug7alq90.apigateway-cn-beijing.volceapi.com/runner"
          mlp-task-id: "${{ needs.setup.steps.create-runner.outputs.mlp_task_id }}"
